services:
  - type: web
    name: askmynotes-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        value: https://askmynotes-sees.onrender.com